### ISSUE TITLE
Will it ever be possible to use the keyword amd64 instead of ~amd64?

### ISSUE THREAD

**Issue by joe9** [sakaki-/funtoo-2-gentoo#3]
Hello,

The ~amd64 branch has a lot of updates. Just want to check if it would ever be possible to use the stable amd64 branch?

Thanks

**Comment by sakaki-** [comment]
I haven't tried this recently. Funtoo is more liberal about stabilization than Gentoo, and so even its 'stable' ebuilds tend to bring in large amounts of `~amd64` stuff from the main Gentoo tree, which you then need to add manually (and transitively!) to `/etc/portage/package.accept_keywords` if you have `ACCEPT_KEYWORDS="amd64"` in `/etc/portage/make.conf` (and this can't be delegated into a profile, unfortunately).

If you **do** want to try running it with `ACCEPT_KEYWORDS="amd64"`, remember to add:

```
*/*::funtoo-2-gentoo ~amd64
```

to `/etc/portage/package.accept_keywords`, so that you continue to get the ebuilds from this overlay.

It's probably easiest to start from scratch with a fresh Gentoo install if you want to try this, rather than downgrading `@world`.

Do let me know how you get on if you go this route! Best, sakaki

**Comment by joe9** [comment]
Hello,

Thanks for your help. That worked like a charm.

I had a blocker on media-libs/mesa. I added "=media-libs/mesa-10.4.6 ~amd64" to package.accept_keywords and that took care of it.

Thanks again,
